-- Migration: [DEPRECATED] Demo data for UC-005 analytics dashboard.
-- Replaced by migration 044_delete_demo_records.sql which cleans up any
-- existing demo records. No-op: all demo seeding is now disabled.
